name: blur
version: 0.1.9.5
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a private & untraceable cryptocurrency based on the cryptonote protocol.
    The Blur Network consists of individuals mining independently on CPUs, without
    the need for specialized hardware. Join the Fight for Financial Freedom.  
grade: stable
confinement: strict

apps:
    blurd:
        command: |
          blurd-wrapper --data-dir ${HOME}/.blur-net
        plugs:
            - network
            - network-bind
    blur-wallet-rpc:
        command: |
          blur-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    blur-wallet-cli:
        command: |
          blur-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=release
            - -DMANUAL_SUBMODULES=1
            - -DBUILD_TESTS=OFF
            - -DARCH=default
            - -DSTATIC=1
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libboost-all-dev
            - libssl-dev
            - libzmq3-dev
            - libpgm-dev
            - libsodium-dev
        stage-packages:
            - libunbound2
            - libboost-date-time1.58.0
            - libboost-serialization1.58.0
            - libboost-chrono1.58.0
            - libboost-system1.58.0
            - libboost-thread1.58.0
            - libboost-locale1.58.0
            - libboost-atomic1.58.0
            - libboost-filesystem1.58.0
            - libboost-program-options1.58.0
            - libboost-regex1.58.0
            - libssl-dev
            - libzmq5
            - libsodium18
            - libstdc++6
            - libgcc1
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/blurd.conf: etc/blurd.conf
            contrib/snap/blurd-wrapper: bin/blurd-wrapper
        prime:
            - etc
            - bin

