name: DPoW Default Branch

on:
  push:
    branches:
      - dpow

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init
    - name: make
      run: make release-cross-linux-x86_64
      env:
        HOST: x86_64-linux-gnu
        BOOST_IGNORE_SYSTEM_PATHS: ON
        CPATH: $CPATH -I/home/runner/work/dpow-blur/dpow-blur/contrib/depends/x86_64-linux-gnu/include
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/home/runner/work/dpow-blur/dpow-blur/contrib/depends/x86_64-linux-gnu/lib
