name: DPoW Testnet Branch

on:
  push:
    branches:
      - testnet

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init
    - name: install-deps
      run: sudo apt-get update && sudo apt-get install libevent-dev
    - name: make
      run: make release-cross-linux-x86_64
      env:
        BOOST_IGNORE_SYSTEM_PATHS: ON
